export const ADD_FILM = 'ADD_FILM'
export const DELETE_FILM = 'DELETE_FILM'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const UPDATE_YEAR = 'UPDATE_YEAR'
export const UPDATE_STARS = 'UPDATE_STARS'
export const UPDATE_FORMAT = 'UPDATE_FORMAT'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const FETCH_FILMS = 'FETCH_FILMS'

